// <auto-generated />
using System;
using DirectoryMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DirectoryMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420192111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("DirectoryMonitor.Models.Entities.EventLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WatchedPathId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WatchedPathId");

                    b.ToTable("EventLogEntries");
                });

            modelBuilder.Entity("DirectoryMonitor.Models.Entities.WatchedPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtensionsFilter")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeSubdirectories")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WatchedPaths");
                });

            modelBuilder.Entity("DirectoryMonitor.Models.Entities.EventLogEntry", b =>
                {
                    b.HasOne("DirectoryMonitor.Models.Entities.WatchedPath", "WatchedPath")
                        .WithMany()
                        .HasForeignKey("WatchedPathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WatchedPath");
                });
#pragma warning restore 612, 618
        }
    }
}
